<!--
  ~ Copyright (c) 2025 In-Game Event, A Red Flag Syndicate LLC.
  ~ All rights reserved.
  ~
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.igearfs</groupId>
    <artifactId>SyncSyndicate-launcher</artifactId>
    <version>1.7.1</version>
    <name>jnlp-launcher</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jfx.version>17.0.2</jfx.version> <!-- Use JavaFX 17 -->
        <maven.compiler.source>17</maven.compiler.source> <!-- JDK 17 -->
        <maven.compiler.target>17</maven.compiler.target> <!-- JDK 17 -->
        <!-- Wix Path for jpackage -->
        <wix.path>wix314-binaries</wix.path> <!-- Replace with your actual Wix path -->
        <target.os>javafx-win-amd64_17</target.os>  <!-- Example value -->
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.microsoft</groupId>
            <artifactId>credential-secure-storage</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!-- CREDENTIAL MANAGERS -->
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.13.0</version>
        </dependency>
        <!-- END CREDENTIAL MANAGERS -->
        <!-- JavaFX dependencies -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${jfx.version}</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${jfx.version}</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-web</artifactId>
            <version>${jfx.version}</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>${jfx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-media</artifactId>
            <version>${jfx.version}</version>
        </dependency>

        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>11.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>${jfx.version}</version>
        </dependency>

        <!-- Exec Maven Plugin for running batch file -->
        <dependency>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.5.0</version>
        </dependency>
        <!-- SLF4J API -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.0</version>
        </dependency>

        <!-- Logback (Logging Framework) -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.5</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
        <repository>
            <id>jcenter</id>
            <url>https://jcenter.bintray.com/</url>
        </repository>
    </repositories>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <!-- Maven Compiler Plugin for JDK 17 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>17</release> <!-- Use release instead of -source and -target -->
                </configuration>
            </plugin>

            <!-- JavaFX Maven Plugin -->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <configuration>
                            <mainClass>com.igearfs.jnlp.Main</mainClass> <!-- Corrected main class -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Maven Shade Plugin to create an executable JAR -->
            <plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.igearfs.jnlp.Main</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Maven Antrun Plugin to Copy the JAR to the jarfile directory -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>copy-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <!-- Delete all SyncSyndicate-1.*.exe files -->
                                <delete>
                                    <fileset dir="${project.basedir}" includes="SyncSyndicate-1.*.exe"/>
                                </delete>
                                <delete dir="${project.basedir}/jnlp_cache" />
                                <mkdir dir="${project.basedir}/jnlp_cache"/>
                                <delete dir="${project.basedir}/jarfile" />
                                <mkdir dir="${project.basedir}/jarfile"/>
                                <copy file="${project.build.directory}/${project.artifactId}-${project.version}.jar"
                                      tofile="${project.basedir}/jarfile/${project.artifactId}-${project.version}.jar"/>
                            </target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>clean-up</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <!-- Delete all SyncSyndicate-1.*.exe files -->
                                <delete>
                                    <fileset dir="${project.basedir}" includes="SyncSyndicate-1.*.exe"/>
                                </delete>
                                <delete dir="${project.basedir}/jnlp_cache" />
                                <mkdir dir="${project.basedir}/jnlp_cache"/>
                                <delete dir="${project.basedir}/jarfile" />
                                <mkdir dir="${project.basedir}/jarfile"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>
    <profiles>
        <profile>
            <id>windows-amd64</id>
            <activation>
                <os>
                    <family>windows</family>
                    <arch>amd64</arch>
                </os>
            </activation>
            <properties>
                <target.os>javafx-win-amd64_17</target.os> <!-- Target directory for JavaFX SDK -->
            </properties>
            <build>
                <plugins>
                    <!-- Download and unzip JavaFX SDK before jpackage build -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <phase>generate-resources</phase> <!-- Ensure it runs before the 'package' phase -->
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target name="download-and-unzip">
                                        <!-- Download the JavaFX SDK -->
                                        <get src="https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_windows-x64_bin-sdk.zip"
                                             dest="${project.build.directory}/openjfx-17.0.2_windows-x64_bin-sdk.zip"
                                             verbose="true" />

                                        <!-- Unzip the JavaFX SDK into the target directory -->
                                        <unzip src="${project.build.directory}/openjfx-17.0.2_windows-x64_bin-sdk.zip"
                                               dest="${project.basedir}/${target.os}/"
                                               overwrite="true" />

                                        <!-- Move the 'lib' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/lib"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- Move the 'legal' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/legal"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- Copy the contents of the 'bin' directory to the 'lib' directory -->
                                        <copy todir="${project.basedir}/${target.os}/lib/">
                                            <fileset dir="${project.basedir}/${target.os}/javafx-sdk-17.0.2/bin" includes="**/*"/>
                                        </copy>

                                        <!-- List the contents of the extracted folder to debug -->
                                        <echo message="Listing extracted files in ${project.basedir}/${target.os}/"/>
                                        <fileset dir="${project.basedir}/${target.os}/" includes="**/*"/>

                                        <!-- Delete the now-empty directory after moving the contents -->
                                        <delete dir="${project.basedir}/${target.os}/javafx-sdk-17.0.2"/>

                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <!-- Your existing exec-maven-plugin to run jpackage build -->
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.5.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>cmd</executable>
                                    <arguments>
                                        <argument>/c</argument>
                                        <argument>${project.basedir}/build-jpackage.bat</argument>
                                        <argument>${project.basedir}/${wix.path}</argument>
                                        <argument>${project.artifactId}-${project.version}.jar</argument>
                                        <argument>${java.home}</argument>
                                        <argument>${project.basedir}/javafx-win-amd64_17</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>macos-x64</id>
            <activation>
                <os>
                    <family>mac</family>
                    <arch>x86_64</arch>
                </os>
            </activation>
            <properties>
                <target.os>javafx-macos-x64</target.os>
            </properties>
            <build>
                <plugins>
                    <!-- Download and unzip JavaFX SDK before jpackage build -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <phase>generate-resources</phase> <!-- Ensure it runs before the 'package' phase -->
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target name="download-and-unzip">
                                        <!-- Download the JavaFX SDK -->
                                        <get src="https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_osx-x64_bin-sdk.zip"
                                             dest="${project.build.directory}/openjfx-17.0.2_osx-x64_bin-sdk.zip"
                                             verbose="true" />

                                        <!-- Unzip the JavaFX SDK into the target directory -->
                                        <unzip src="${project.build.directory}/openjfx-17.0.2_osx-x64_bin-sdk.zip"
                                               dest="${project.basedir}/${target.os}/"
                                               overwrite="true" />

                                        <!-- Move the 'lib' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/lib"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- Move the 'legal' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/legal"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- List the contents of the extracted folder to debug -->
                                        <echo message="Listing extracted files in ${project.basedir}/${target.os}/"/>
                                        <fileset dir="${project.basedir}/${target.os}/" includes="**/*"/>

                                        <!-- Delete the now-empty directory after moving the contents -->
                                        <delete dir="${project.basedir}/${target.os}/javafx-sdk-17.0.2"/>

                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.5.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>/bin/bash</executable>
                                    <arguments>
                                        <argument>${project.basedir}/build-osx.sh</argument>
                                        <argument>${project.artifactId}-${project.version}.jar</argument>
                                        <argument>${java.home}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>macos-arm64</id>
            <activation>
                <os>
                    <family>mac</family>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <properties>
                <target.os>javafx-macos-arm64_17</target.os>
            </properties>
            <build>
                <plugins>
                    <!-- Download and unzip JavaFX SDK before jpackage build -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <phase>generate-resources</phase> <!-- Ensure it runs before the 'package' phase -->
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target name="download-and-unzip">
                                        <!-- Download the JavaFX SDK -->
                                        <get src="https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_osx-x64_bin-sdk.zip"
                                             dest="${project.build.directory}/openjfx-17.0.2_osx-x64_bin-sdk.zip"
                                             verbose="true" />

                                        <!-- Unzip the JavaFX SDK into the target directory -->
                                        <unzip src="${project.build.directory}/openjfx-17.0.2_osx-x64_bin-sdk.zip"
                                               dest="${project.basedir}/${target.os}/"
                                               overwrite="true" />

                                        <!-- Move the 'lib' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/lib"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- Move the 'legal' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/legal"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- List the contents of the extracted folder to debug -->
                                        <echo message="Listing extracted files in ${project.basedir}/${target.os}/"/>
                                        <fileset dir="${project.basedir}/${target.os}/" includes="**/*"/>

                                        <!-- Delete the now-empty directory after moving the contents -->
                                        <delete dir="${project.basedir}/${target.os}/javafx-sdk-17.0.2"/>

                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.5.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>/bin/bash</executable>
                                    <arguments>
                                        <argument>${project.basedir}/build-osx.sh</argument>
                                        <argument>${project.artifactId}-${project.version}.jar</argument>
                                        <argument>${java.home}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>linux-arm64</id>
            <activation>
                <os>
                    <family>linux</family>
                    <arch>aarch64</arch> <!-- ARM64 architecture -->
                </os>
            </activation>
            <properties>
                <target.os>javafx-linux-aarch64</target.os>
            </properties>
            <build>
                <plugins>
                    <!-- Download and unzip JavaFX SDK before jpackage build -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <phase>generate-resources</phase> <!-- Ensure it runs before the 'package' phase -->
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target name="download-and-unzip">
                                        <!-- Download the JavaFX SDK -->
                                        <get src="https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_linux-aarch64_bin-sdk.zip"
                                             dest="${project.build.directory}/openjfx-17.0.2_linux-aarch64_bin-sdk.zip"
                                             verbose="true" />

                                        <!-- Unzip the JavaFX SDK into the target directory -->
                                        <unzip src="${project.build.directory}/openjfx-17.0.2_linux-aarch64_bin-sdk.zip"
                                               dest="${project.basedir}/${target.os}/"
                                               overwrite="true" />

                                        <!-- Move the 'lib' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/lib"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- Move the 'legal' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/legal"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- List the contents of the extracted folder to debug -->
                                        <echo message="Listing extracted files in ${project.basedir}/${target.os}/"/>
                                        <fileset dir="${project.basedir}/${target.os}/" includes="**/*"/>

                                        <!-- Delete the now-empty directory after moving the contents -->
                                        <delete dir="${project.basedir}/${target.os}/javafx-sdk-17.0.2"/>

                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.5.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>/bin/bash</executable>
                                    <arguments>
                                        <argument>${project.basedir}/build-linux-arm64.sh</argument>
                                        <argument>${project.artifactId}-${project.version}.jar</argument>
                                        <argument>${java.home}</argument>
                                        <argument>${project.basedir}/javafx-linux-aarch64</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>linux-x64</id>
            <activation>
                <os>
                    <family>linux</family>
                    <arch>x86_64</arch> <!-- x86_64 architecture -->
                </os>
            </activation>
            <properties>
                <target.os>javafx-linux-amd64</target.os>
            </properties>
            <build>
                <plugins>
                    <!-- Download and unzip JavaFX SDK before jpackage build -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <phase>generate-resources</phase> <!-- Ensure it runs before the 'package' phase -->
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target name="download-and-unzip">
                                        <!-- Download the JavaFX SDK -->
                                        <get src="https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_linux-x64_bin-sdk.zip"
                                             dest="${project.build.directory}/openjfx-17.0.2_linux-x64_bin-sdk.zip"
                                             verbose="true" />

                                        <!-- Unzip the JavaFX SDK into the target directory -->
                                        <unzip src="${project.build.directory}/openjfx-17.0.2_linux-x64_bin-sdk.zip"
                                               dest="${project.basedir}/${target.os}/"
                                               overwrite="true" />

                                        <!-- Move the 'lib' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/lib"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- Move the 'legal' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/legal"
                                              todir="${project.basedir}/${target.os}/" />


                                        <!-- List the contents of the extracted folder to debug -->
                                        <echo message="Listing extracted files in ${project.basedir}/${target.os}/"/>
                                        <fileset dir="${project.basedir}/${target.os}/" includes="**/*"/>

                                        <!-- Delete the now-empty directory after moving the contents -->
                                        <delete dir="${project.basedir}/${target.os}/javafx-sdk-17.0.2"/>

                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.5.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>/bin/bash</executable>
                                    <arguments>
                                        <argument>${project.basedir}/build-linux-x64.sh</argument>
                                        <argument>${project.artifactId}-${project.version}.jar</argument>
                                        <argument>${java.home}</argument>
                                        <argument>${project.basedir}/javafx-linux-amd64</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>linux-x86</id>
            <activation>
                <os>
                    <family>linux</family>
                    <arch>x86</arch> <!-- x86 architecture for 32-bit -->
                </os>
            </activation>
            <properties>
                <target.os>javafx-linux-arm32</target.os>
            </properties>
            <build>
                <plugins>
                    <!-- Download and unzip JavaFX SDK before jpackage build -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <phase>generate-resources</phase> <!-- Ensure it runs before the 'package' phase -->
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target name="download-and-unzip">
                                        <!-- Download the JavaFX SDK -->
                                        <get src="https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_linux-arm32_bin-sdk.zip"
                                             dest="${project.build.directory}/openjfx-17.0.2_linux-arm32_bin-sdk.zip"
                                             verbose="true" />

                                        <!-- Unzip the JavaFX SDK into the target directory -->
                                        <unzip src="${project.build.directory}/openjfx-17.0.2_linux-arm32_bin-sdk.zip"
                                               dest="${project.basedir}/${target.os}/"
                                               overwrite="true" />

                                        <!-- Move the 'lib' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/lib"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- Move the 'legal' folder up one level -->
                                        <move file="${project.basedir}/${target.os}/javafx-sdk-17.0.2/legal"
                                              todir="${project.basedir}/${target.os}/" />

                                        <!-- List the contents of the extracted folder to debug -->
                                        <echo message="Listing extracted files in ${project.basedir}/${target.os}/"/>
                                        <fileset dir="${project.basedir}/${target.os}/" includes="**/*"/>

                                        <!-- Delete the now-empty directory after moving the contents -->
                                        <delete dir="${project.basedir}/${target.os}/javafx-sdk-17.0.2"/>

                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.5.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>/bin/bash</executable>
                                    <arguments>
                                        <argument>${project.basedir}/build-linux-arm32.sh</argument>
                                        <argument>${project.artifactId}-${project.version}.jar</argument>
                                        <argument>${java.home}</argument>
                                        <argument>${project.basedir}/javafx-linux-arm32</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!--        <profile>-->
<!--            <id>osx-amd64</id>-->
<!--            <activation>-->
<!--                <os>-->
<!--                    <family>mac</family>-->
<!--                    <arch>x86_64</arch>-->
<!--                </os>-->
<!--            </activation>-->
<!--            <build>-->
<!--                <plugins>-->
<!--                    <plugin>-->
<!--                        <groupId>org.codehaus.mojo</groupId>-->
<!--                        <artifactId>exec-maven-plugin</artifactId>-->
<!--                        <version>3.5.0</version>-->
<!--                        <executions>-->
<!--                            <execution>-->
<!--                                <phase>package</phase>-->
<!--                                <goals>-->
<!--                                    <goal>exec</goal>-->
<!--                                </goals>-->
<!--                                <configuration>-->
<!--                                    <executable>bash</executable>-->
<!--                                    <arguments>-->
<!--                                        <argument>${project.basedir}/build-linux-x64.sh</argument>-->
<!--                                        <argument>${project.artifactId}-${project.version}.jar</argument>-->
<!--                                        <argument>${java.home}</argument>-->
<!--                                    </arguments>-->
<!--                                </configuration>-->
<!--                            </execution>-->
<!--                        </executions>-->
<!--                    </plugin>-->
<!--                </plugins>-->
<!--            </build>-->
<!--        </profile>-->
<!--        <profile>-->

    </profiles>
</project>
